[package]
name = "crypto-summary"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.6", features = ["json"] }
tokio = { version = "1.13.0", features = ["full"] }
serde_json = "1.0"
serde = { version = "1", features = ["derive"] }
clap = "2"
url = "2.2.2"
csv = "1.1.6"
